Increment13
dreamersole/go_url_shortener pull request #14
Opened 2022-02-08 13:09 UTC by dreamersole

2022-02-09 18:26 UTC, Bazys requested changes
предлагаю воспользоваться рекомендациями из курса по работе с Postgres.
Упростит жизнь во многих случаях

2022-02-09 18:26 UTC, Bazys commented on internal/app/shortener/handler.go
> +	statusCode := 201
не очень правильно использовать константы. в рельной жизни линтер не пропустит такое.
есть константы из пакета http

2022-02-09 18:26 UTC, Bazys commented on internal/app/shortener/handler.go
> +		http.Error(w, "User auth error", 500)
это нвверное 403 ошибка?

2022-02-09 18:26 UTC, Bazys commented on internal/app/shortener/handler.go
> +		http.Error(w, "User auth error", 500)
аналогично 403

2022-02-09 18:26 UTC, Bazys commented on internal/app/shortener/postgres_storage.go
> +	dbIsEmpty := err1a != nil && err1b != nil && err2a != nil && err2b != nil
очен рекомендую это распутать!

2022-02-09 18:26 UTC, Bazys commented on internal/app/shortener/postgres_storage.go
> +			create table shortener_users(
всего выше можно избежать если использовать конструкцию if exists

2022-02-09 18:26 UTC, Bazys commented on internal/app/shortener/postgres_storage.go
> +		INSERT INTO shortener_urls (url, user_id) VALUES ($1, $2) RETURNING id;
а как же рекомендации из курса про `INSERT ... ON CONFLICT` ?

2022-02-10 14:00 UTC, dreamersole commented on internal/app/shortener/handler.go
> +	statusCode := 201
Согласен, заменил на константы из пакета http

2022-02-10 14:03 UTC, dreamersole commented on internal/app/shortener/handler.go
> +		http.Error(w, "User auth error", 500)
Да, 403

2022-02-10 16:34 UTC, dreamersole commented on internal/app/shortener/postgres_storage.go
> +			create table shortener_users(
Упростил создание БД, используя конструкцию create table if not exists
Но после этого оставил простой запрос к БД для проверки структуры таблиц (вдруг кто-то заранее создал таблицы с теми же именами, но с другой структурой)

2022-02-10 20:04 UTC, dreamersole commented on internal/app/shortener/postgres_storage.go
> +		INSERT INTO shortener_urls (url, user_id) VALUES ($1, $2) RETURNING id;
Оптимизировал:
1. Добавил в БД дополнительный индекс (по полям url и user_id)
2. Применил конструкцию ON CONFLICT в функциях URLAddRecord и URLAddRecordBatch

2022-02-11 10:23 UTC, dreamersole commented
В целом:
1. Использовал предопределенные константы модуля http для возврата статуса, исправил ошибочные коды статуса
2. Упростил создание БД, используя конструкцию create table if not exists
3. Заменил Query на QueryRow там, где это можно
4. Использовал заранее подготовленные SQL операторы (prepared statements)
5. Добавил в БД дополнительный индекс (по полям url и user_id)
6. Применил конструкцию ON CONFLICT в функциях URLAddRecord и URLAddRecordBatch
7. Оптимизировал текст SQL запросов

2022-02-11 10:54 UTC, dreamersole commented
И в итоге выяснил важную вещь - statement prepare можно делать только ПОСЛЕ того, как база данных и таблицы уже созданы

2022-02-13 08:37 UTC, dreamersole commented on internal/app/shortener/file_storage.go
> +		if err != nil {
Согласен, id, ok & err - выглядят немного избыточно
Я не стал объединять ok & err, потому что !ok - это не совсем ошибка, а скорее индикатор того, что id не найден,
и на вызывающей стороне err и ok обрабатываются в разных ветвях логики
С другой стороны, в стандартной библиотеке есть ошибки типа EOF и т. п., так что наверное можно и объединить
Кроме того, у меня была мысль объединить id & ok
например, если id не найден, возвращать специальное значение id == 0
Но тогда я так и не пришел к единому решению и решил оставить как есть id, ok & err

2022-02-16 16:06 UTC, merged